app:
  port: :80

log:
  level: info #debug / info / warn / error / dpanic / panic / fatal
  filename: ./logs/prod.log
  maxSize: 100 #MB
  maxAge: 1 #days
  maxBackups: 15

mysql:
  dsn: root:admin123@tcp(localhost:3306)/app-layout?charset=utf8mb4
